Add Docker container for MSSQL for Linux
DapperLib/DapperAOT pull request #3
Opened 2021-05-05 14:47 UTC by khalidabuhakmeh

This let's folks run the benchmark regardless of their
host operating system. Previously it was SQLExpress.

🐳

2021-05-05 14:48 UTC, khalidabuhakmeh commented
My benchmarks for funnzies. 

// * Summary *

BenchmarkDotNet=v0.12.1, OS=macOS 11.3.1 (20E241) [Darwin 20.4.0]
Intel Core i7-9750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=6.0.100-preview.3.21202.5
  [Host]        : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Job=.NET Core 5.0  Runtime=.NET Core 5.0  

|                 Method |     Mean |     Error |    StdDev |   Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------- |---------:|----------:|----------:|---------:|------:|------:|------:|----------:|
|       DapperSystemData | 1.293 ms | 0.0258 ms | 0.0378 ms | 1.293 ms |     - |     - |     - |   3.63 KB |
|    DapperMicrosoftData | 1.343 ms | 0.0304 ms | 0.0822 ms | 1.330 ms |     - |     - |     - |   3.75 KB |
|    DapperAOTSystemData | 1.549 ms | 0.1045 ms | 0.2930 ms | 1.449 ms |     - |     - |     - |   2.06 KB |
| DapperAOTMicrosoftData | 1.373 ms | 0.0299 ms | 0.0839 ms | 1.366 ms |     - |     - |     - |   1.97 KB |

2021-05-08 06:52 UTC, mgravell requested changes
Hugely appreciated; that's an approach I haven't seen before, looks good! A couple of minor nits. The format changes - meh, I'm not precious, but I'll check whether we're going to run into reformat problems - but if so, I should probably add an editor config file (that's on me).

Can I also check that you're able and willing (and thus doing) to freely contribute code in accordance with the stated project license? (purely a formality)

2021-05-08 06:52 UTC, mgravell commented on test/UsageBenchmark/Program.cs
> +        public static string ConnectionString
Nit: could be const?

2021-05-08 06:52 UTC, mgravell commented on test/UsageBenchmark/Program.cs
> +            container.Dispose();
This seems redundant - there's a `using` above

2021-05-08 06:52 UTC, mgravell commented on test/UsageBenchmark/Program.cs
> +            string cs = Program.ConnectionString;
Just use Program.ConnectionString in place of `cs`, i.e. nuke `cs`?

2021-05-08 06:52 UTC, mgravell commented on test/Dapper.AOT.Test/SamplesTests.cs
> +            var inputPath = File.ReadAllText(path);
👍

2021-05-08 06:52 UTC, mgravell commented on test/Dapper.AOT.Test/SamplesTests.cs
> +                    && Path.GetDirectoryName(originFile) is { } originFolder)
nit: subjective, but I think I prefer the `is string` syntax (or `is not null` if we aren't capturing the value) when we're not using the `{...}` to test members - for clarity reasons

2021-05-08 06:52 UTC, mgravell commented on test/UsageBenchmark/Program.cs
> +                new Builder()
👍 nice; will definitely use this approach for the integration test fixture, too

2021-05-13 18:20 UTC, khalidabuhakmeh commented
Ah! I was too slow. I'm going to close this PR and submit another PR. Seems some of the structure changed in the file and rebasing seem like a PITA.

2021-05-13 18:32 UTC, closed without merging